accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.home_view, name='home'),
    path('register/',views.register, name='register'),
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),
    path('write/',views.write, name='write'),
]

calc/urls.py
from django.urls import path
from . import views

app_name = 'calc'

urlpatterns = [
    path('',views.home_view, name='home'),
    path('add_view/',views.add_view, name='add_view'),
    path('mult_view/',views.mult_view, name='mult_view'),
    path('sub_view',views.sub_view, name='sub_view'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('calc/', include('calc.urls')),
    path('travello/', include('travello.urls')),
    path('', include('accounts.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travello/urls.py
from django.urls import path
from . import views

app_name = 'travello'

urlpatterns = [
    path('',views.home_view, name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

calc/models.py
from django.db import models

# Create your models here.

travello/models.py
from django.db import models

# Create your models here.

class Destination(models.Model):
    #id : int
    name = models.CharField(max_length=100)
    desc = models.TextField()
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages

from travello.models import Destination


def home_view(request):
    return render(request, 'accounts/home.html')

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password1 = request.POST['password1']
        passsword2 = request.POST['password2']
        email = request.POST['email']

        #Checks
        if password1==passsword2:
            if User.objects.filter(username=username).exists():
                messages.info(request,'Username already taken')
                return redirect('accounts:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'E-Mail already taken')
                return redirect('accounts:register')
            else:
                user = User.objects.create_user(username=username, password=password1, email=email, first_name=first_name, last_name=last_name)
                user.save()
                messages.info(request, 'user created')
                return redirect('accounts:login')
        else:
            messages.info(request, 'Password not matching')
            return redirect('accounts:register')
    else: # Dann ist die Method GET
        return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect("/")
        else:
            messages.info(request, 'invalid credentials')
            return redirect('accounts:login')
    elif request.method == 'GET':
        return render(request, 'accounts/login.html')

def write(request):
    if request.method == 'GET':
        return render(request, 'accounts/write.html')
    elif request.method == 'POST':
        # Userinputs in Variablen speichern
        ort=request.POST['name']
        beschreibung=request.POST['desc']
        preis=int(request.POST['price'])

        newdest = Destination.objects.create() #Object anlegen
        #Objectattribute beschreiben
        newdest.name=(ort)
        newdest.desc = (beschreibung)
        newdest.price = (preis)
        newdest.save() #In die Datenbank speichern
        return redirect('travello:home')


def logout(request):
    auth.logout(request)
    return redirect('accounts:home')

calc/views.py
from django.shortcuts import render, redirect
from django.urls import reverse


def home_view(request):
    return render(request,'calc/home.html')

def add_view(request):
    if request.method == 'POST':
        val1 = float(request.POST['num1'])
        val2 = float(request.POST['num2'])
        res = val1 + val2
        return render(request, 'calc/result.html', {'result': res})
    elif request.method == 'GET':
        return render(request, 'calc/add_view.html')

def mult_view(request):
    if request.method == 'POST':
        val1 = float(request.POST['num1'])
        val2 = float(request.POST['num2'])
        res = val1 * val2
        return render(request, 'calc/result.html', {'result': res})
    elif request.method == 'GET':
        return render(request, 'calc/mult_view.html')

def sub_view(request):
    if request.method == 'POST':
        val1 = float(request.POST['num1'])
        val2 = float(request.POST['num2'])
        res = val1 - val2
        return render(request, 'calc/result.html', {'result': res})
    elif request.method == 'GET':
        return render(request, 'calc/sub_view.html')

travello/views.py
from django.shortcuts import render
from .models import Destination

def home_view(request):
    dests = Destination.objects.all()
    return render(request, 'travello/home.html', {'dests':dests})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        {% endblock %}</title>
</head>
<body>
    <div class="page-header">
        <h1>Das ist Adrians Website</h1>
        <a href="{% url 'accounts:home' %}">Home Website</a>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div>
        {% for message in messages %}
        <h3> {{message}} </h3>
        {% endfor %}
    </div>
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <a href="{% url 'calc:home' %}">Calculator App</a>
    <br>

    <a href="{% url 'travello:home' %}">Travello App</a>
    <br>
    <br>
    {% if user.is_authenticated %}
        <p>Hello. You are logged in</p>
        <a href="{% url 'accounts:logout' %}">Logout</a>
        <br>
        <p>Schreibe einen neuen Travello Betrag</p>
        <a href="{% url 'accounts:write' %}">Neuen Beitrag erstellen<a>
    {% else %}
        <a href="{% url 'accounts:register' %}">Registrieren</a>
        <a href="{% url 'accounts:login' %}">Login</a>
    {% endif %}
    <br>
    <br>
    <a href="admin/">Admin Zugang</a>
    {% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>
<p>Bitte geben Sie folgendes ein:</p>
<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>
    <input type="password" name="password" placeholder="Password"><br>
    <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<h2>Registrierung</h2>
<p>Bitte geben Sie folgendes ein:</p>
<form method="post" action="{% url 'accounts:register' %}">
    {% csrf_token %}
    <input type="text" name="first_name" placeholder="First Name"><br>
    <input type="text" name="last_name" placeholder="Last Name"><br>
    <input type="text" name="username" placeholder="Username"><br>
    <input type="email" name="email" placeholder="email"><br>
    <input type="password" name="password1" placeholder="Password"><br>
    <input type="password" name="password2" placeholder="Confirm Password"><br>
    <input type="submit">
</form>
{% endblock %}

accounts/templates/accounts/write.html
{% extends 'accounts/base.html' %}

{% block title %}Write{% endblock %}

{% block content %}
<h2>Schreibe einen neuen Artikel für die Travllo-App</h2>
<p>Bitte geben Sie folgendes ein:</p>
<form method="post" action="{% url 'accounts:write' %}">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Ort eingeben"><br>
    <input type="text" name="desc" placeholder="Beschreibung eingeben"><br>
    <input type="integer" name="price" placeholder="Preis eigeben"><br>
    <input type="submit">
</form>
{% endblock %}

calc/templates/calc/add_view.html
{% extends 'calc/base.html' %}

{% block title %}Addieren{% endblock %}

{% block content %}
<p>Addieren:</p>
<form method="post" action="{% url 'calc:add_view' %}">
    {% csrf_token %}
    Enter first number: <input type="text" name="num1"> <br>
    Enter second number: <input type="text" name="num2"> <br>
    <input type="submit">
</form>
{% endblock %}

calc/templates/calc/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        {% endblock %}</title>
</head>
<body>
    <div class="page-header">
        <h1>Calculator App</h1>
        <a href="{% url 'accounts:home' %}">Home Website</a>
        <br>
        <a href="{% url 'calc:home' %}">Home Calculator App</a>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

calc/templates/calc/home.html
{% extends 'calc/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<p>Was möchten Sie berechnen? </p>
<a href="{% url 'calc:add_view' %}">Addieren</a>
<br>
<a href="{% url 'calc:mult_view' %}">Multiplizieren</a>
<br>
<a href="{% url 'calc:sub_view' %}">Subtrahieren</a>

{% endblock %}

calc/templates/calc/mult_view.html
{% extends 'calc/base.html' %}

{% block title %}Multiplizieren{% endblock %}

{% block content %}
<p>Multiplizieren:</p>
<form method="post" action="{% url 'calc:mult_view' %}">
    {% csrf_token %}
    Enter first number: <input type="text" name="num1"> <br>
    Enter second number: <input type="text" name="num2"> <br>
    <input type="submit">
</form>
{% endblock %}

calc/templates/calc/result.html
{% extends 'calc/base.html' %}

{% block title %}Result{% endblock %}

{% block content %}
<p>Hier ist das Ergebnis: {{result}} </p>
{% endblock %}

calc/templates/calc/sub_view.html
{% extends 'calc/base.html' %}

{% block title %}Subtrahieren{% endblock %}

{% block content %}
<p>Subtrahieren:</p>
<form method="post" action="{% url 'calc:sub_view' %}">
    {% csrf_token %}
    Enter first number: <input type="text" name="num1"> <br>
    Enter second number: <input type="text" name="num2"> <br>
    <input type="submit">
</form>
{% endblock %}

travello/templates/travello/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        {% endblock %}</title>
</head>
<body>
    <div class="page-header">
        <h1>Travello</h1>
        <a href="{% url 'accounts:home' %}">Home Website</a>
        <br>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

travello/templates/travello/home.html
{% extends 'travello/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<h2>Das Travello Home</h2>
<p>Die Inhalte werden von PostgreSQL geladen</p>
<br>
{% for dest in dests %}
<p>---------------------------------</p>
<p> ID: {{dest.id}}</p>
<p> Ort: {{dest.name}}</p>
<p> Beschreibung: {{dest.desc}}</p>
<p> Preis: {{dest.price}}</p>
{% endfor %}
{% endblock %}